#!/bin/bash
figlet Update All
# Start Of The Script:
echo -en '\n'
echo -e "Small Script for Updating and Upgrading Packages on Linux \e[7m(ubuntu20.04 OS)\e[27m"
echo 'Version 1.0'
echo -en '\n'
echo -en '\n'

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
#Checking Update:
echo -e "\e[31mChecking for updates...\e[0m"
echo -e "\e[32mUpdates are found! \e[0m"
# Main:
apt autoremove -y && apt --fix-broken install && apt update --fix-missing || error '\e[31mUnable to update, please check your internet connection...\e[0m' && apt upgrade -y && apt autoremove -y
echo -en && sudo apt install -f
#Comment 'clear' below to stop clearing the output:
clear -x
# Ending:
echo "All is updated, press X to exit"
count=0
while : ; do
read -n 1 k <&1
if [[ $k = x ]] ; then
printf "\nQuitting from the script...\n"
break
else
((count=$count+1))
printf "\nWrong key pressed for $count times\n"
echo "Press X to exit"
fi
done

